n = input('Say something ')
print('The primitive type is')
print(type(n))
print('this is alphabetic')
print(n.isalpha())  
print('This was written in capital letters only')
print(n.isupper())
print('this is alphanumeric')
print(n.isalnum())
print('This is numeric')
print(n.isnumeric())
print('this is a digit')
print(n.isdigit())
print('This is a decimal number')
print(n.isdecimal())

